spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: blog
server:
  port: 8081 #端口号
uploadDir:
  D:/nginx-image/image/
static:
  image:
      path: http://localhost/image/